name: Docker Image CI
on:
  push:
    branches: master
  pull_request:
    branches: master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag canberktest:$(date +%s)
  trigger:
    name: Dispatch to `other-repo`
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Dispatch workflow
     #   run: |
     #       curl \
     #       -X PUT \
     #       -H "Accept: application/vnd.github+json" \
     #       -H "Authorization: Bearer ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
     #        https://api.github.com/repos/canberkaslan/test_actions_cd/actions/workflows/3020658793/disable
        run: |
          curl -XPOST -u "${{ secrets.PERSONAL_ACCESS_TOKEN }}" -H "Accept:application/vnd.github" -H "Content-Type:application/json"  https://api.github.com/repos/canberkaslan/test_actions_cd/contents/.github/workflows/main.yaml/dispatches --data '{"ref": "main" }'
    #   uses: convictional/trigger-workflow-and-wait@v1.6.1
    #   with:
    #      owner: canberkaslan
    #      repo: 'test_actions_cd'
    #      github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    #      workflow_file_name: main.yml